### ISSUE TITLE
Return Response in SetWebhook method

### ISSUE THREAD

**Issue by eefret** [Syfaro/telegram-bot-api#17]
For consistency its good to have the response feedback from this API method, I could even submit a PR doing this, it will be trivial, anyway I like how you have done this API client, its awesome, thanks.

**Comment by Syfaro** [comment]
Telegram does not document the response for a setWebook request, is there anything in the response that contains useful information? I just realized I've never really taken a look at that before.

**Comment by eefret** [comment]
This is an example of what the response looks like, its a simple APIResponse:
```
    {
        ok: true,
        result: true,
        description: "Webhook was set"
    }
```

If you agree I can do a PR to do that simple change, as I would like to contribute to this project :)

**Comment by Syfaro** [comment]
That'd be lovely!
