### ISSUE TITLE
Update setWebhook method to support for self signed certificate Feature

### ISSUE THREAD

**Issue by eefret** [Syfaro/telegram-bot-api#18]
From Telegram Bot Api oficial page:

Recent changes

August 29, 2015

Added support for self-signed certificates: upload your certificate using the certificate parameter in the setWebhook method.

**Comment by Syfaro** [comment]
Yep, it definitely needs this feature. 

I'll work on this now.

**Comment by Syfaro** [comment]
Would it be easier to have people specify a file with the certificate public key, or just a string version of that? Or maybe both?

**Comment by eefret** [comment]
Will check the type of cert required, if its CACERT then must be a file

**Comment by eefret** [comment]
According to the telegram documentation it needs a file, we can do the same as in #20 so we have the flexibility to send either a ReaderCloser, bytes or a File.

**Comment by Syfaro** [comment]
I haven't tested this function yet, but it should work. 

https://github.com/Syfaro/telegram-bot-api/commit/ca40caaa47e6bcb38d5dbf5c85fc87d2f689683e

**Comment by eefret** [comment]
Yeah it should. Thnx
