### ISSUE TITLE
Update to support Webhook responses 

### ISSUE THREAD

**Issue by eefret** [Syfaro/telegram-bot-api#19]
From telegram bot api official page:

Recent changes

August 29, 2015
You can now make new requests when responding to webhook updates.

Would be cool to have a helper method to ease this task.

**Comment by Syfaro** [comment]
Responding to webhooks really doesn't seem like a great idea, it doesn't let you ever get the status of that response. Having to make an extra request really shouldn't affect anything that significantly.
