### ISSUE TITLE
Add the option to send Reader or [] bytes in fileSending methods (sendPictures, sendAudio, sendDocument)

### ISSUE THREAD

**Issue by eefret** [Syfaro/telegram-bot-api#20]
Some of us (like me) have their bots in GAE (Google App Engine) since the sendPicture method only takes a file path it can't be used in GAE because the system is readonly so would be cool to add a param or override those methods that send files picture, audio, document, etc to have to posiblity to send a ReaderCloser (like response.Body) or a []bytes that can be parsed inside them.

This is an example on how I achieved this with the same library you're using:

```
    ms.WriteReader(paramType, "card." + extension, contentLength, resp.Body)
	req, _ := http.NewRequest("POST", BASE_URL + methodName, nil)
	ms.SetupRequest(req)
```

**Comment by Syfaro** [comment]
I believe that this commit should resolve this issue, let me know if there's any issues with it!
