### ISSUE TITLE
More flexible logging options

### ISSUE THREAD

**Issue by nvx** [Syfaro/telegram-bot-api#25]
At the moment this library does not allow a developer to replace the golang default log package to capture logs to redirect to say syslog as is common with services.

This is mainly apparent in the UpdatesChan goroutine when an error occurs during the poll.

**Comment by Syfaro** [comment]
What would you suggest doing? A `chan` for errors?

Is there anywhere else this is an issue besides `UpdateChan`?

**Comment by nvx** [comment]
I've been trying to work out what the most idiomatic pattern would be for this, but have come up short so far sadly.

Perhaps a log interface then a logger instance can be passed in (either the standard golang logger, or any of the other loggers that implement identical methods)?

**Comment by Syfaro** [comment]
I wonder if it wouldn't just be easier to implement the function in your own code, considering the entire thing is 18 lines of code.

**Comment by nvx** [comment]
hmm point, I had kind of expected it to rely on internal functions but it seems it doesn't.

If the functions used by it are considered public and not likely to change to private, then that  does seem like a decent option in this case!

**Comment by Syfaro** [comment]
All it's doing is looping a call to `BotAPI.GetUpdates`, which is always going to stay public. 

I'm going to close this issue. If anyone has suggestions later, feel free to mention them and I'll reopen it!

**Comment by fabulias** [comment]
@Syfaro maybe we can use logrus instead log pkg because logrus offer a lot of logging layers (panic, debug, info, error, fatal, etc).

**Comment by vietvudanh** [comment]
I am having this problem too. I am using Uber's zap, with jsonl format. The internal logger keep printing out logs, e.g `getUpdates resp:/req`. Of course those lines cannot be parsed and be ignored awn, but I am wondering if there is a way to centralize the loggers.
