### ISSUE TITLE
Demo project build error

### ISSUE THREAD

**Issue by vioir** [Syfaro/telegram-bot-api#26]
Hi
I've got a problem when i try to build the Demo project in visual studio 2015.
![errors](https://cloud.githubusercontent.com/assets/13207882/10264079/a0c2f9b0-6a0f-11e5-83f0-a71bb40acf87.JPG)
![filebrowser](https://cloud.githubusercontent.com/assets/13207882/10264081/aad41c7c-6a0f-11e5-9cc8-33ed081c4b3a.JPG)

**Comment by Syfaro** [comment]
I do believe you're on the wrong repo, this library is for golang, not C#.
