### ISSUE TITLE
APIResponse contents discarded other than Result

### ISSUE THREAD

**Issue by nvx** [Syfaro/telegram-bot-api#27]
I've been having an issue with a Telegram Bot silently failing to send messages intermittently. The SendPhoto function is returning error == nil in such cases indicating no failure occurred but the message has not delivered.

While looking into what could cause a nil error while still having an error I noticed that the APIResponce returned by MakeRequest is not checked at all, more specifically the Ok and ErrorCode fields.

While I haven't monkeypatched anything in yet to see if the server is rejecting my sent messages gracefully, it seems like this library should be checking the values or at least making the APIResponse accessible to the user user code if required.

**Comment by Syfaro** [comment]
It looks like `MakeRequest` is working correctly, it checks if `Ok` is not true. 

I do believe that `UploadFile` is not correct, in that it does not check if the request was `Ok`. 

Please let me know if this was not fixed by 0d2feed6c26a7bd6c5458e970afd1f72a21d0dd8.

**Comment by nvx** [comment]
Ah yup you're right. For some reason I thought both were affected (although I was only using UploadFile).

Looks like that commit should fix it so I'll close this issue. Cheers!
