### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by pyed** [Syfaro/telegram-bot-api#31]
I'm failing to send a document or a video which is considered not too small, something like ~60Mb, with the debug set to true, the following lines will be shown:

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.9.1</center>
</body>
</html>
```

the code

```go
package main

import (
	"log"

	"github.com/Syfaro/telegram-bot-api"
)

func main() {
	bot, err := tgbotapi.NewBotAPI("DatToken")
	if err != nil {
		log.Panic(err)
	}

	bot.Debug = true

	log.Printf("Authorized on account %s", bot.Self.UserName)

	u := tgbotapi.NewUpdate(0)
	u.Timeout = 60

	updates, err := bot.GetUpdatesChan(u)

	for update := range updates {
		log.Printf("[%s] %s", update.Message.From.UserName, update.Message.Text)

		msg := tgbotapi.NewDocumentUpload(update.Message.Chat.ID, "NotTooSmallOfaFile")

		bot.Send(msg)
	}
}
```

**Comment by Syfaro** [comment]
['Bots can currently send files of any type of up to 50 MB in size, this limit may be changed in the future'](https://core.telegram.org/bots/api#senddocument)

**Comment by oalmeida593** [comment]
def send_audio_to_telegram(file_path, chat_id, bot_token):
    """Envia um arquivo de áudio para o Telegram, dividindo-o em partes se necessário"""
    url = f"https://api.telegram.org/bot{bot_token}/sendAudio"
    try:
        for part_number, chunk in enumerate(split_file(file_path)):
            # Cria um nome de arquivo para a parte
            part_file_name = f"{os.path.splitext(file_path)[0]}_parte{part_number + 1}.mp3"
            with open(part_file_name, 'wb') as part_file:
                part_file.write(chunk)  # Escreve o chunk em um novo arquivo

            with open(part_file_name, 'rb') as audio_file:
                response = requests.post(url, data={'chat_id': chat_id}, files={'audio': audio_file})
                response.raise_for_status()  # Levanta um erro se a resposta não for 200
            print(f"Parte enviada: {part_file_name}")  # Adicionado para imprimir o nome da parte enviada
    except requests.exceptions.RequestException as e:
        print(f"Erro ao enviar áudio: {e}")  # Exibe o erro
