### ISSUE TITLE
Please stop changing things!

### ISSUE THREAD

**Issue by twitchyliquid64** [Syfaro/telegram-bot-api#32]
Twas using this in production, couldnt figure out why the weekly autobuild was failing till I looked at the logs....

~~I dont think anyone really cares if the method is called UpdatesChan as opposed to GetUpdatesChan, or Send vs SendMessage, but I can say that if every time I git pull things break because someone likes one naming scheme better I would be looking for a different library.~~

^ Strikethrough cuz rude. What I mean to say is this: when you release a project that ends up being used heavilly in many other projects, you need to have some stability

Some ideas going forward:

1. Create new methods and deprecate old ones. A fancy way of doing this is to make the old methods print something to STDERR, that cannot be disabled without moving to the new methods. Gently lets users know without breaking things.
2. Branch / fork to new repository.
3. Document procedures for how methods will be removed/added, and provide api-lock guarantees.

**Comment by twitchyliquid64** [comment]
![image](https://cloud.githubusercontent.com/assets/6328589/11649747/57bcaf36-9dd6-11e5-84f9-65c7d2816195.png)

<3

**Comment by Syfaro** [comment]
I apologize for making breaking changes that were so minor. 

I will definitely take your suggestions into consideration if the need to change things arrises again, although I do not anticipate anything soon.
