### ISSUE TITLE
Don't unmarshal the result

### ISSUE THREAD

**Issue by emadgh** [Syfaro/telegram-bot-api#4]
As I see, all the result recieved from telegram server are getting unmarshal, it's an unneeded thing,
Users can do'it their self or you could put an option that if they want it to unmarshal the result...

It would save a lot of time for server as we know Json (Un)Marshaling is a little slow in Golang...

Thanks in advance @Syfaro

**Comment by Syfaro** [comment]
What's the use case for not unmarshalling the data? 

Additionally, how much of a performance difference could there be in so few and such small messages? It seems like an unnecessary micro-optimization.

**Comment by Syfaro** [comment]
I'm just going to close this now.
