### ISSUE TITLE
More tests

### ISSUE THREAD

**Issue by Syfaro** [Syfaro/telegram-bot-api#7]
What else can be tested?

**Comment by eefret** [comment]
You can do `go test -coverprofile=testinfo` and then `go tool cover -html=testinfo` to see the percentage of code covered by your tests.

**Comment by Syfaro** [comment]
It's more of a question of what should be tested, as so much relies on the Telegram API and this doesn't have much logic.

**Comment by zhulik** [comment]
@Syfaro you can close it, a lot of tests already here!
